export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_GRADED_ASSIGNMENT_LIST_START =
  "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
  "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const GET_TEST_LIST_START = "GET_TEST_LIST_START";
export const GET_TEST_LIST_FAIL = "GET_TEST_LIST_FAIL";
export const GET_TEST_LIST_SUCCESS = "GET_TEST_LIST_SUCCESS";

export const GET_TEST_DETAIL_START = "GET_TEST_DETAIL_START";
export const GET_TEST_DETAIL_FAIL = "GET_TEST_DETAIL_FAIL";
export const GET_TEST_DETAIL_SUCCESS = "GET_TEST_DETAIL_SUCCESS";

export const CREATE_TEST_START = "CREATE_TEST_START";
export const CREATE_TEST_FAIL = "CREATE_TEST_FAIL";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";

export const GET_GRADED_TEST_LIST_START =
  "GET_GRADED_TEST_LIST_START";
export const GET_GRADED_TEST_LIST_FAIL =
  "GET_GRADED_TEST_LIST_FAIL";
export const GET_GRADED_TEST_LIST_SUCCESS =
  "GET_GRADED_TEST_LIST_SUCCESS";

export const UPDATE_GRADED_TEST_LIST_START =
  "UPDATE_GRADED_TEST_LIST_START";
export const UPDATE_GRADED_TEST_LIST_FAIL =
  "UPDATE_GRADED_TEST_LIST_FAIL";
export const UPDATE_GRADED_TEST_LIST_SUCCESS =
  "UPDATE_GRADED_TEST_LIST_SUCCESS";